### ISSUE TITLE
Does not compile with new versions of OpenSSL (>1.1.0)

### ISSUE THREAD

**Issue by ilya-a-sergeyev** [MFrcoin/MFCoin#11]
Debian 9 x86_64
```
openssl version
OpenSSL 1.1.0f  25 May 2017
```

```
src/bignum.h:51:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
                        ^~~~~~
In file included from /usr/include/openssl/crypto.h:31:0,
                 from src/allocators.h:12,
                 from src/qt/walletmodel.h:8,
                 from src/qt/bitcoin.cpp:9:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
In file included from src/main.h:8:0,
                 from src/wallet.h:13,
                 from src/init.h:8,
                 from src/qt/bitcoin.cpp:13:
```

**Comment by alex-mamchenkov** [comment]
The problem is with openssl version. You need version 1.0.1.
